# --------------- Database ----------------
# %player% - converts to player (target) name.
# %time_left% - shows time left to claim daily reward.

# rules:
# color codes are supported, for example &a, HEX codes are allowed too.
# commands needs to be written without the slash char (  /  )

# --------------- Database ----------------
# Options: LOCAL, MYSQL

DATABASE: LOCAL
CREDENTIALS:
  USERNAME: ''
  PASSWORD: ''
  DATABASE: ''
  HOST: 127.0.0.1
  PORT: 3306

# -------------- Language --------------

# CommandAPI messages
MESSAGE_NOT_ENOUGH_PERMISSIONS: "&cNot enough permissions!"
MESSAGE_PLAYER_ONLY: "&cThis command can not be performed in console!"
MESSAGE_CONSOLE_ONLY: "&cThis command can not be performed in game!"
MESSAGE_RELOAD: "&aSuccessfully reloaded all configurations."

# Permissions
PERMISSION_ADMIN_ONLY: "reward.admin"

# Plugin messages
MESSAGE_SUCCESS: "&aSuccessfully claimed your &edaily reward"
MESSAGE_NOT_YET: "&cYou can not claim your daily reward yet. Wait for another %time%."
MESSAGE_DB_SUCCESS: "&aSuccessfully connected to MySQL."
MESSAGE_SUCCESS_REMOVE: "&aSuccessfully removed player data!"
MESSAGE_SUCCESS_PURGE: "&aSuccessfully purged player data!"
MESSAGE_ERROR: "&cError! If you see this message, you probably messed something up in your config.yml"
MESSAGE_ERROR_TABLES: "An error has occured while creating tables (MySQL)"
# MESSAGE_ERROR_MONGO: "&cThere was an error "
MESSAGE_ARGS_REWARD: "&cCorrect usage &7/reward &cor &7/reward <VIP name>"
MESSAGE_ARGS_PURGE: "&cCorrect usage &7/reward purge <mysql, mongodb>"
MESSAGE_ARGS_REMOVE: "&cCorrect usage &7/reward remove <player>"
MESSAGE_NO_PLAYER: "&cThis player does not exist in database!"
MESSAGE_WRONG_TYPE: "&cWrong data type in config.yml (DATABASE)"
MESSAGE_CLOSE_DATABASE: "&aClosing database connection!"

# -------- Plugin configuration --------
# Important stuff
ENABLE_PREFIX: true
PREFIX: "&c&lDailyReward &7&l» &r"

# Options: HOUR, MIDNIGHT
TIME_FORMAT: HOUR

# Day multiplier
DAYS_TO_WAIT: 1

# --------------- Rewards --------------
# Basic reward
DEFAULT_REWARD:
  PERMISSION: "reward.default"
  MESSAGE: "&aYou've received your daily reward."
  COMMANDS:
    - "eco give %player% 200"
    - "give %player% coal 2"

# VIP (Amazing) reward
AMAZING_REWARD:
  PERMISSION: "reward.amazing"
  MESSAGE: "&aYou've received your premium (&2Amazing&a) daily reward."
  COMMANDS:
    - "eco give %player% 200"
    - "give %player% iron_ingot 2"

# VIP (Lion) reward
LION_REWARD:
  PERMISSION: reward.lion
  MESSAGE: "&aYou've received your premium (&2Lion&a) daily reward."
  COMMANDS:
    - "eco give %player% 200"
    - "give %player% gold_ingot 2"

# VIP (Cruel) reward
CRUEL_REWARD:
  PERMISSION: reward.cruel
  MESSAGE: "&aYou've received your premium (&2Cruel&a) daily reward."
  COMMANDS:
    - "eco give %player% 200"
    - "give %player% diamond 2"