# --------------- Database ----------------
# %player% - converts to player (target) name.
# %time_left% - shows time left to claim daily reward.

# rules:
# color codes are supported, for example &a, HEX codes are allowed too.
# commands needs to be written without the slash char (  /  )

# --------------- Database -----------------
# Options: LOCAL, MYSQL

DATABASE: 'LOCAL'
CREDENTIALS:
  USERNAME: ''
  PASSWORD: ''
  DATABASE: ''
  HOST: 127.0.0.1
  PORT: 3306

# ---------------- Language ----------------

# CommandAPI messages
MESSAGE_NOT_ENOUGH_PERMISSIONS: "&9Not enough &cpermissions&9!"
MESSAGE_PLAYER_ONLY: "&cThis command can not be performed in console!"
MESSAGE_CONSOLE_ONLY: "&cThis command can not be performed in game!"
MESSAGE_RELOAD: "&9Successfully reloaded all configurations."

# -------------- Permissions ---------------
# Permission for reload, purge and remove command
PERMISSION_ADMIN_ONLY: "reward.admin"

# Plugin messages
MESSAGE_SUCCESS: "&9Successfully claimed your &edaily reward"
MESSAGE_NOT_YET: "&9You can not claim your daily reward yet. &9Wait for another &a%time%&9."
MESSAGE_SUCCESS_REMOVE: "&aSuccessfully removed player data!"
MESSAGE_SUCCESS_PURGE: "&aSuccessfully purged player data!"
MESSAGE_ERROR: "&cError! If you see this message, you probably messed something up in your config.yml"
MESSAGE_ERROR_TABLES: "&cAn error has occured while creating tables (MySQL)"
MESSAGE_ARGS_REWARD: "&9Correct usage &a/reward &9or &a/reward <VIP name>"
MESSAGE_ARGS_PURGE: "&9Correct usage &a/reward purge <MySQL, MongoDB>"
MESSAGE_ARGS_REMOVE: "&9Correct usage &a/reward remove <player>"
MESSAGE_ARGS_ERROR: "&cWrong usage of the command! Did you mean to use &4%command%?"
MESSAGE_NO_PLAYER: "&9This player &cis not &9in that database!"
MESSAGE_WRONG_TYPE: "&cWrong data type in config.yml!"
MESSAGE_DB_DISCONNECT: "&aClosing database connection!"
MESSAGE_DB_SUCCESS: "&aSuccessfully connected to database."
MESSAGE_DB_ERROR: "&cThere was an error with chosen database!"

# -------- Plugin configuration --------
# Important stuff
ENABLE_PREFIX: true
PREFIX: "&9&lDailyReward &7&l» &r"

# Options: HOUR, MIDNIGHT
TIME_FORMAT: HOUR

# Day multiplier
DAYS_TO_WAIT: 1

# --------------- Rewards --------------
# Basic reward
DEFAULT_REWARD:
  PERMISSION: "reward.default"
  MESSAGE: "&aYou've received your daily reward."
  COMMANDS:
    - "eco give %player% 200"
    - "give %player% coal 2"

# VIP (Amazing) reward
AMAZING_REWARD:
  PERMISSION: "reward.amazing"
  MESSAGE: "&aYou've received your premium (&2Amazing&a) daily reward."
  COMMANDS:
    - "eco give %player% 200"
    - "give %player% iron_ingot 2"

# VIP (Lion) reward
LION_REWARD:
  PERMISSION: reward.lion
  MESSAGE: "&aYou've received your premium (&2Lion&a) daily reward."
  COMMANDS:
    - "eco give %player% 200"
    - "give %player% gold_ingot 2"

# VIP (Cruel) reward
CRUEL_REWARD:
  PERMISSION: reward.cruel
  MESSAGE: "&aYou've received your premium (&2Cruel&a) daily reward."
  COMMANDS:
    - "eco give %player% 200"
    - "give %player% diamond 2"

# Experimental
REWARDS:
  DEFAULT:
    PERMISSION: "reward.default"
    MESSAGE: "&aYou've received your daily reward."
    COMMANDS:
      - "eco give %player% 200"
      - "give %player% coal 2"

  AMAZING:
    PERMISSION: "reward.amazing"
    MESSAGE: "&aYou've received your premium (&2Amazing&a) daily reward."
    COMMANDS:
      - "eco give %player% 200"
      - "give %player% iron_ingot 2"